# Generated by Django 4.2.4 on 2023-12-15 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='boxes',
            field=models.ManyToManyField(blank=True, related_name='subboxes', to='box.box'),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tagged_items', to='box.unit'),
        ),
    ]
