# Generated by Django 4.2.4 on 2023-12-18 22:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0004_remove_item_barcode_itemportion_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemportion',
            name='barcode',
            field=models.ImageField(blank=True, default='C:\\Users\\Eddie Tang\\PythonProjects\\djangobox\\djangobox\\media\\barcodes\\notbarcode.png', upload_to='barcodes'),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('qty_returned', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('timestamp_borrow', models.DateTimeField()),
                ('timestamp_return', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('b', 'Borrowed'), ('p', 'Partially Returned'), ('r', 'Fully Returned')], default='b', help_text='Loan status', max_length=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.itemportion')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp_borrow'],
            },
        ),
    ]
