# Generated by Django 4.2.4 on 2023-12-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0005_alter_itemportion_barcode_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(blank=True, choices=[('n', 'None Returned'), ('p', 'Partially Returned'), ('r', 'Fully Returned')], default='n', help_text='Loan status', max_length=1),
        ),
    ]
