# Generated by Django 4.2.4 on 2023-12-18 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0006_alter_loan_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='boxes',
        ),
        migrations.AddField(
            model_name='box',
            name='boxes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subboxes', to='box.box'),
        ),
    ]
