# Generated by Django 4.2.4 on 2023-12-18 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0007_remove_box_boxes_box_boxes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='boxes',
            new_name='box',
        ),
    ]
