# Generated by Django 4.2.4 on 2023-12-18 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0008_rename_boxes_box_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='box.location'),
        ),
    ]
