# Generated by Django 4.2.4 on 2024-01-01 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0009_alter_box_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemportion',
            old_name='uuid',
            new_name='slug',
        ),
    ]
