# Generated by Django 4.2.4 on 2024-01-05 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0010_rename_uuid_itemportion_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemportion',
            name='barcode',
            field=models.ImageField(blank=True, default='/Users/eddie/pythonprojects/djangobox/djangobox/media/barcodes/notbarcode.png', upload_to='barcodes'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='box.itemportion'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='timestamp_borrow',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
