# Generated by Django 4.2.4 on 2024-01-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0011_alter_itemportion_barcode_alter_loan_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(blank=True, choices=[('n', 'None Returned'), ('p', 'Partially Returned'), ('r', 'Fully Returned')], default='n', editable=False, help_text='Loan status', max_length=1),
        ),
    ]
