# Generated by Django 4.2.4 on 2024-01-06 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0012_alter_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='box.itemportion'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='timestamp_return',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to=settings.AUTH_USER_MODEL),
        ),
    ]
