# Generated by Django 4.2.4 on 2024-01-06 18:57

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0013_alter_loan_item_alter_loan_timestamp_return_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='slug',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22),
        ),
    ]
