# Generated by Django 4.2.4 on 2024-01-06 19:31

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0014_box_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='slug',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22),
        ),
    ]
