# Generated by Django 4.2.4 on 2024-01-06 19:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0015_loan_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
